name: parse_dart
description: A Dart/Flutter SDK for Parse Server - feature-complete clone of Parse JS SDK
version: 0.1.0
repository: https://github.com/parse-community/Parse-SDK-JS
issue_tracker: https://github.com/parse-community/Parse-SDK-JS/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # HTTP Client
  dio: ^5.4.0
  
  # JSON Serialization
  json_annotation: ^4.8.0
  freezed_annotation: ^3.1.0
  
  # Utilities
  uuid: ^4.3.0
  equatable: ^2.0.5
  intl: ^0.20.2
  meta: ^1.11.0


dev_dependencies:
  # Code Generation
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  freezed: ^3.2.3
  
  # Testing
  test: ^1.24.0
  mockito: ^5.4.0
  mocktail: ^1.0.0
  
  # Linting
  lints: ^6.0.0
