name: parse_dart
description: A Dart SDK for Parse Server
version: 0.1.0
repository: https://github.com/2shrestha22/parse_dart
issue_tracker: https://github.com/2shrestha22/parse_dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  uuid: ^4.3.0
  equatable: ^2.0.5
  meta: ^1.11.0


dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
